name: Notebook CI

on:
  push:
    branches:
      - dev

jobs:
  convert-nbs:
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: dev
        token: ${{ secrets.GIT_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Configure git
      run: |
        git config --global user.name "nb ci bot"
        git config --global user.email "<>"
    - name: Setup python environment
      run: |
        pip install --upgrade pip
        pip install jupyter
    - name: Convert notebooks
      run: |
        chmod +x ./git-filter-repo
        for FILE in $(find . -type f -name "*.ipynb"); do
          jupyter nbconvert --to script $FILE
          git add ${FILE%.ipynb}.py
          git commit -m "Converting nb $FILE"
          ./git-filter-repo --force --path $FILE --invert-paths
        done
    - name: Push to main
      run: |
        git push origin dev:main -f
