name: Notebook CI

on:
  push:
    branches:
      - main

jobs:
  lock-branch:
    runs-on: ubuntu-latest
    needs: convert-nbs
    if: ${{ always() }}
    environment: actions
    steps:=
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Setup python environment
      run: |
        pip install --upgrade pip
        pip install requests
    - name: Lock branch
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        python lock_branch.py --lock

  convert-nbs:
    runs-on: ubuntu-latest
    needs: lock-branch
    environment: actions
    steps:=
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Setup python environment
      run: |
        pip install --upgrade pip
        pip install jupyter
    - name: Configure git
      run: |
        git config --global user.name "nb ci bot"
        git config --global user.email "<>"
    - name: Convert notebooks
      run: |
        ORIGN="$(git remote get-url origin)"
        for FILE in $(find . -type f -name "*.ipynb"); do
          jupyter nbconvert --to script $FILE
          git add ${FILE%.ipynb}.py
          git commit -m "Converting nb ${FILE:2}"
          ./git-filter-repo --force --path ${FILE:2} --invert-paths
        done
        git remote add origin "$ORIGIN" || :
    - name: Push edits to main
      run: |
        git push origin main:main -f

  unlock-branch:
    runs-on: ubuntu-latest
    needs: convert-nbs
    if: ${{ always() }}
    environment: actions
    steps:=
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Setup python environment
      run: |
        pip install --upgrade pip
        pip install requests
    - name: Lock branch
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        python lock_branch.py
