name: Notebook CI

on:
  push:
    branches:
      - main

jobs:
  convert-nbs:
    runs-on: ubuntu-latest
    environment: actions
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TOKEN }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Configure git
      run: |
        git log > .gitlog
        cat .gitlog
        git config --global user.name "nb ci bot"
        git config --global user.email "<>"
        echo ""
        echo ""
        echo ""
        echo ""
        echo ""
        git log > .gitlog
        cat .gitlog
    - name: Setup python environment
      run: |
        pip install --upgrade pip
        pip install jupyter
    - name: Save git state
      run: |
        git log > .gitlog
        git remote get-url origin > .gitorigin
    - name: Convert notebooks
      run: |
        for FILE in $(find . -type f -name "*.ipynb"); do
          jupyter nbconvert --to script $FILE
          git add ${FILE%.ipynb}.py
          git commit -m "Converting nb ${FILE:2}"
          ./git-filter-repo --force --path ${FILE:2} --invert-paths
        done
    - name: Save edits
      run: |
        # rename current setup as unique branch
        BRANCH=main-$RANDOM
        git branch -m $BRANCH

        # restore origin (lost w/ git history edit)
        git remote add origin "$(cat .gitorigin)"

        # get main's state, to check for updates since action started
        git clone "$(cat .gitorigin)" .main

        echo $(cd .main && git log)
        echo ""
        echo ""
        echo ""
        echo ""
        cat .gitlog

        # push to main, if this action is still for the latest commit
        if [[ $(cd .main && git log) == $(cat .gitlog) ]]; then
          git checkout $BRANCH
          git push origin $BRANCH:main -f
        fi
